/* The reference syllabus we measure ourselves against.
 *
 * Every topic W3Schools teaches in its core Python tutorial (plus its DSA and
 * Reference sections), mapped to the DataMarg lesson that covers it. `covers: []`
 * means nothing covers it yet — that is the point of the file. Run
 * `npm run syllabus` to see the scoreboard.
 *
 * Sections that belong to other DataMarg tracks (Matplotlib, MySQL, MongoDB,
 * Machine Learning, NumPy/Pandas) are deliberately not listed here — this file
 * is about the Python track only.
 */

export const SYLLABUS = [
  { group: "Getting started", topics: [
    { t: "Python Intro — what it is, why it is used", covers: ["getting-started"] },
    { t: "Get Started — running your first program", covers: ["getting-started"] },
    { t: "Syntax and indentation", covers: ["getting-started"] },
    { t: "Output / print()", covers: ["getting-started"] },
    { t: "Comments", covers: ["getting-started"] },
    { t: "User Input", covers: ["getting-started"] },
  ]},
  { group: "Variables and types", topics: [
    { t: "Variables — creating and reassigning", covers: ["variables-data-types"] },
    { t: "Variable names — rules and conventions", covers: ["variables-data-types"] },
    { t: "Assign multiple values / unpacking", covers: ["variables-data-types"] },
    { t: "Output variables", covers: ["variables-data-types"] },
    { t: "Global variables / global keyword", covers: ["scope"] },
    { t: "Data types overview", covers: ["variables-data-types"] },
    { t: "Numbers — int, float, complex", covers: ["numbers-math"] },
    { t: "Casting", covers: ["variables-data-types"] },
    { t: "None", covers: [] },
  ]},
  { group: "Strings", topics: [
    { t: "Strings — basics and quotes", covers: ["strings"] },
    { t: "Slicing strings", covers: ["strings"] },
    { t: "Modify strings — upper, lower, strip, replace", covers: ["strings"] },
    { t: "Concatenate strings", covers: ["strings"] },
    { t: "Format strings / f-strings", covers: ["string-formatting"] },
    { t: "Escape characters", covers: [] },
    { t: "String methods — full reference", covers: [] },
  ]},
  { group: "Booleans and operators", topics: [
    { t: "Booleans and truthiness", covers: ["booleans"] },
    { t: "Arithmetic operators", covers: ["operators"] },
    { t: "Assignment operators (+=, -=)", covers: ["operators"] },
    { t: "Comparison operators", covers: ["operators"] },
    { t: "Logical operators (and/or/not)", covers: ["operators"] },
    { t: "Identity operators (is / is not)", covers: ["more-operators"] },
    { t: "Membership operators (in / not in)", covers: ["more-operators"] },
    { t: "Bitwise operators", covers: ["more-operators"] },
    { t: "Ternary / shorthand if", covers: ["conditionals"] },
    { t: "Operator precedence", covers: ["operators"] },
  ]},
  { group: "Lists", topics: [
    { t: "Lists — basics", covers: ["lists-tuples"] },
    { t: "Access list items / indexing", covers: ["lists-tuples"] },
    { t: "Change list items", covers: ["lists-tuples"] },
    { t: "Add list items — append, insert, extend", covers: ["lists-tuples"] },
    { t: "Remove list items — remove, pop, del, clear", covers: ["lists-tuples"] },
    { t: "Loop through a list", covers: ["loops"] },
    { t: "List comprehension", covers: ["comprehensions"] },
    { t: "Sort lists", covers: [] },
    { t: "Copy lists", covers: [] },
    { t: "Join lists", covers: [] },
    { t: "List methods — full reference", covers: [] },
  ]},
  { group: "Tuples, sets, dictionaries", topics: [
    { t: "Tuples — basics and immutability", covers: ["lists-tuples"] },
    { t: "Tuple unpacking", covers: [] },
    { t: "Tuple methods", covers: [] },
    { t: "Sets — basics", covers: ["dicts-sets"] },
    { t: "Add / remove set items", covers: ["dicts-sets"] },
    { t: "Join sets — union, intersection, difference", covers: [] },
    { t: "Frozenset", covers: [] },
    { t: "Set methods — full reference", covers: [] },
    { t: "Dictionaries — basics", covers: ["dicts-sets"] },
    { t: "Access / change / add / remove dict items", covers: ["dicts-sets"] },
    { t: "Loop through a dictionary", covers: ["dicts-sets"] },
    { t: "Copy a dictionary", covers: [] },
    { t: "Nested dictionaries", covers: [] },
    { t: "Dictionary methods — full reference", covers: [] },
  ]},
  { group: "Control flow", topics: [
    { t: "If / elif / else", covers: ["conditionals"] },
    { t: "Nested if", covers: ["conditionals"] },
    { t: "pass statement", covers: [] },
    { t: "match-case", covers: ["match-case"] },
    { t: "While loops", covers: ["loops"] },
    { t: "For loops", covers: ["loops"] },
    { t: "break / continue / else on loops", covers: ["loops"] },
    { t: "range()", covers: [] },
  ]},
  { group: "Functions", topics: [
    { t: "Functions — def and calling", covers: ["functions"] },
    { t: "Arguments and default values", covers: ["functions"] },
    { t: "*args and **kwargs", covers: ["advanced-functions"] },
    { t: "Return values", covers: ["functions"] },
    { t: "Scope — local, global, LEGB", covers: ["scope"] },
    { t: "Lambda", covers: ["lambda"] },
    { t: "Recursion", covers: ["advanced-functions"] },
    { t: "Decorators", covers: ["decorators"] },
    { t: "Generators and yield", covers: ["iterators-generators"] },
    { t: "Iterators — iter / next", covers: ["iterators-generators"] },
    { t: "Arrays (array module vs list)", covers: [] },
  ]},
  { group: "OOP", topics: [
    { t: "Classes and objects", covers: ["oop"] },
    { t: "__init__ constructor", covers: ["oop"] },
    { t: "self parameter", covers: ["oop"] },
    { t: "Class vs instance properties", covers: [] },
    { t: "Class methods and static methods", covers: ["dunder-methods"] },
    { t: "@property / getters and setters", covers: [] },
    { t: "Inheritance", covers: ["inheritance"] },
    { t: "Multiple inheritance and MRO", covers: [] },
    { t: "Polymorphism", covers: ["encapsulation"] },
    { t: "Encapsulation — private attributes", covers: ["encapsulation"] },
    { t: "Dunder / magic methods", covers: ["dunder-methods"] },
    { t: "Inner classes", covers: [] },
  ]},
  { group: "Errors, files, modules", topics: [
    { t: "try / except / else / finally", covers: ["error-handling"] },
    { t: "raise and assert", covers: [] },
    { t: "Custom exception classes", covers: [] },
    { t: "File handling — open modes", covers: ["file-handling"] },
    { t: "Read files", covers: ["file-handling"] },
    { t: "Write / create files", covers: ["file-handling"] },
    { t: "Delete files", covers: [] },
    { t: "Modules — import, from, as", covers: ["modules"] },
    { t: "if __name__ == '__main__'", covers: [] },
    { t: "Packages and __init__.py", covers: [] },
    { t: "PIP — installing packages", covers: ["modules"] },
    { t: "Virtual environments", covers: ["modules"] },
    { t: "Dates and time", covers: ["dates"] },
    { t: "Math module", covers: ["numbers-math"] },
    { t: "JSON", covers: ["json"] },
    { t: "RegEx", covers: ["regex"] },
    { t: "Random module", covers: [] },
  ]},
  { group: "DSA (interview-critical, we have none)", topics: [
    { t: "Big-O / complexity", covers: [] },
    { t: "Arrays and lists as data structures", covers: [] },
    { t: "Stacks", covers: [] },
    { t: "Queues", covers: [] },
    { t: "Linked lists", covers: [] },
    { t: "Hash tables", covers: [] },
    { t: "Trees", covers: [] },
    { t: "Binary trees / binary search trees", covers: [] },
    { t: "Graphs", covers: [] },
    { t: "Linear search", covers: [] },
    { t: "Binary search", covers: [] },
    { t: "Bubble / selection / insertion sort", covers: [] },
    { t: "Merge / quick sort", covers: [] },
  ]},
  { group: "Reference (lookup pages, we have none)", topics: [
    { t: "Built-in functions reference", covers: [] },
    { t: "String methods reference", covers: [] },
    { t: "List / tuple methods reference", covers: [] },
    { t: "Dict / set methods reference", covers: [] },
    { t: "File methods reference", covers: [] },
    { t: "Keywords reference", covers: [] },
    { t: "Exceptions reference", covers: [] },
  ]},
  { group: "Beyond W3Schools (our own edge)", topics: [
    { t: "Testing — unittest / pytest", covers: ["testing"] },
    { t: "Debugging and logging", covers: ["debugging-logging"] },
    { t: "Clean code, PEP 8, type hints", covers: ["clean-code"] },
    { t: "Project structure and git", covers: ["project-git"] },
    { t: "Concurrency — threads and processes", covers: ["concurrency"] },
    { t: "Async / asyncio", covers: ["async"] },
    { t: "collections, itertools, functools", covers: ["collections-itertools"] },
    { t: "os, sys, pathlib", covers: ["system-modules"] },
    { t: "CSV, pickle, SQLite", covers: ["data-persistence"] },
  ]},
];
